export const sponsoringBusinesses = [
  "Artists' Gallery",
  'axgard',
  'B&O Ellicott City Station Museum',
  'Bohemian House',
  'Candles by Candy',
  'Chesapeake Shakespeare Company',
  'CMC Exotics',
  'Crazy Mason Milkshake Bar',
  'Deep Roots Movement',
  'DMV Elite FC',
  'Ellicott City Partnership',
  'Ellicott Distilling Co.',
  "Ellicott Mills Children's Museum",
  'Gamers-Corps',
  'Ghost Town Odditorium',
  'Gracie Renich Art',
  'Howard County Arts Council',
  'Ink & Ivy Studio',
  'Little Market cafe',
  'Main Street Ballroom at Fetewell',
  'Maryland History Tours',
  'Museum of Howard County History',
  "Old Ellicott City Farmers' Market",
  'Patapsco Female Institute',
  'Phoenix Flow Art',
  'Phoenix Upper Main',
  'Ready Set Stitch',
  'Syriana Cafe & Restaurant',
  'The Clayground Studio & Gallery',
  'The Cycle Mill Bike Shop',
  'Time Warp Media',
  'Umi Sushi',
  'Walter Levy Photography',
  'Yatha Yoga',
];

export function getRandomBusiness(): string {
  return sponsoringBusinesses[Math.floor(Math.random() * sponsoringBusinesses.length)];
}
